spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      database: users_db
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - email
              - profile
            redirect-uri: ${prep-pilot.frontend-url}/login/oauth2/code/google

jwt:
  secret: "${JWT_SECRET}"
  access-token-expiry-ms: 1800000   # 30 minutes
  refresh-token-expiry-days: 30

frontend:
  origin: ${prep-pilot.frontend-url}

app:
  caching:
    regions:
      users:
        maximum-size: 100000
        expire-after-write: 12h

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8081
