spring:
  application:
    name: topic-service
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      database: topics_db
      auto-index-creation: true

app:
  caching:
    regions:
      topics:
        maximum-size: 50000
        expire-after-write: 12h

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8082

ai-service:
  internal-api-key: "${INTERNAL_API_KEY}"
