spring:
  application:
    name: topic-service
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      database: topics_db
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8082

ai-service:
  internal-api-key: "${INTERNAL_API_KEY}"
