prep-pilot:
  frontend-url: https://prep-pilot-sable-one.vercel.app
  topic-service-url: https://preppilot-topic.onrender.com
  user-service-url: https://preppilot-user.onrender.com
  ai-service-url: https://interview-prep-pilot-ai.vercel.app